language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...
  - go vet ./..

script:
  - go test ./cmd/sensors -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)