language: go

go:
  - 1.11.x
  - tip

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u github.com/haya14busa/goverage

install:
  - dep ensure

script:
  - goverage -v -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
