language: go

go:
  - 1.8.x
before_script:
  - go get ./...
  - go fmt ./...
  - go vet ./...
  - go test ./...
script:
  -  go test ./cmd/yfirbord -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
