language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
  - ".pioenvs"
env:
  global:
  - secure: cuWLUTT7Oegnt9GJ2qHDjpUtfOStNhsh4GyAcEvUCYwz1Y8CQrEcAbGUKVHkE3BnW4d27sRuHhVqQbgLc7KyhKBCrTDpt8zhky3qPYWnwdCe0w7CYXzrUuGcGx+y1L7ej7Hxar9DK064PLxTkI6xTYtIVcn+qJUCp5tL/qlaL1tNXxG6dZHWX5lScJsNzeR2Pkyx2as+hbZnvtXKl4UbXI4xmUXDamJiSu+iDH039hzD15nVDkXciQ7hfhzSEMBZShO/pzbr7+KhncRLMXYFSWZocQySC3w6nQtpMn4oZgQ7wklNihYCrS03xN2NivFMh7qNVGJlfNRsW1GCbHW63TFCfGT40gCDkU1cVf43qgHP6LjtZIbI7O1UhLjHPE/RWDpJ7B5XhruzyEOP2E4BZpb+XEtH/7h5QxrNV3inkVfUc0kEIJ3mNGYUuziG9pASINWau7GZ7si4U/Pyj2U6ujcfGTfJRaxxuiALmlTf3hHE4dX0YDwuWo4vEy+/hcD45qVy0n0TBohimzeYwBghsK+NiAc50DYGfNUnh140pXHlXhfwGmcw5IyZDXEToR7vDd3bXVU/I8osLVN20M66pI0KxA/LLCHHnH1e+pnk9eMt+Rp4NIDsgEIkbvx94/DUW0LShDJt2ylddK16jgdJyuIahr3xhfnRLb+AaPTY86A=
  - secure: TPEYJzl7NUC0gb7mmlORy5lDPAAcGZ80Bae0VD38EqXq256Nsx0rEpSuBBc8JQdNWGMc7OPu5LieN8t5zuzXrh3yyWCtP0PZPzqDu63SOTF0Nt7M5uVWkagkxPJTEbhOOHT40SfFzy36d0NtUnnVzraqBm2u6nIKW6vkIXnmydud7dkeqjupmsLCi8AcP4NCuIiq/CNXEgVcsKHAYFA0Ujug5s7Ef8ttG5YJOybAU/QVRtvaGde068rKiU6DRC5OQjQJkE2cWI65tC7r6OsNbwd3vTn/GDtM3JvdRujkdr1XvknVaiYJuXzjgWVwlhzcnvlc4jzBDyyVD2AKf6ANB9BggXi9nzAm0HZ6EmWCc4gBZOhystG0j3LlWAWvILZ3Ori53jqDHwA+u3XwDBAfyuZxuiy8eAilEatscsd6RJu3do3qVMGvi10jnMhsN+omYpZmzKf1JrrkLFr5nZFF7ru8Maq0Y+BUGHReeXdpDXCy7ymyzdz4LVrPXBSgDCwdj+VXrs/bSeC4vRuGSC7JAXLGpd6qFF82hg8diTW8HLfLQH0xrKcmodo4R1pwNgmeMpywy5kBGX+hjbk4zafTdaZ4xyEuVzURKZOqEkyO8bOuKLUdc6YXrg/aEdOYXsgs7mNTBgWCdLIcYFqJzJhJUPmmZbjNEtJvbJqH4S1REy4=
  - secure: vImro8fo51vTHKX8tsDZAC4z2FoafgRbz0YADh3rO6be5vjpWdnysYEZqeqgXUEalbPXjffRfU0qUZpLScxyAZ8tAJYVIe4a/dyiXbh7mp9YliThFToxT2o0Boa6foDnq3EEQA5EFB7O7HNJUXHWCkMxkcrlYSw4ldxKEesk10DnHWCYJjYRrQea42RRbzq3CXbQg/CuQO3C+UZ0BbiplTI2D+VT/PZ+8gPeE2ZKbPwHNLQ3J0xLgp8oGgtIHa3BilS59Wk14ZH8LTO5rzt03lfeueNlbrIjoz556GccGgr5Q4Tf52mJDwDZ3mQprBw0NIdei6zdl0OHgrV9DG+PJLDJ9Ie3Fk8TN4RNoYbK91D5/SLr8S8sofoAFLKeNKPfcxmoDKSvujAC/fd9Q5HEwl2R2XYNHhx4lSjwtHZQY9wHE/3Dm2b6QGC73k4PEcfNduAfBUWwnzICOMv3Fd11AbWyiOBbkwghf07s7M/zsoO2P+rUgp5DbhqALRD+euwRBnYOx5dIIG1EGmPDqwpyURn1AkaD3qPd6gaLSW63JnBXKTPuu/11fJmLpeDPa/WQWUCztt3LOk0zJbEEbj76pvpu6pR+SW+oinHHSYf9yOtQIGYWQ09QibiBEWl5Urs17VaA/GZo/kOObf+anAc7MyCdHa7L1dqJSeFLsRUlU74=
install:
- pip install -U platformio
- platformio update
jobs:
  include:
  - stage: build
    script: platformio run
  - stage: release
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: hDWCX/Hv/h1ql7TJQwb+Wzv/fGdIkxNhlRf36XfsN/Bz68HvF8W7zZ6hha/ZbAeZ/2xy+iJ5eBU3e4fya4aDaMdUlIA7vu+zZ872tjlW8qKrVfij4fOcLdgjz/wo6P9qNBfpkXokBimGyMc257TRE7gwa7NQJ6txxSq6Ifuy+fDxOtPNKdkp5VCkOtlJ9Z8QS591NYYZU1El1OgmwvJgMPXl73j8QIWU7RUBjIvCMsK62w/UKdJWwNCx4in+UdpkTjsfiyMxlgBGLI2g4llawclQp226d3YHhaRrqLI/Z4Xdt3pGA/hkG0HwVGRvHcRoQfcfXfIDyCxK2uWakWHhLzok9SS0c9vdRjrqDsJfp0URDxaUiv7fEwO5njCmd8DBib+wr5o9fRFr/L8PKiI913Ru4StivUWg/cWp0kVtIQ84N56zF3U8AvZgDbSVmisrpHvl4pc6ZTvA6xC0pMM0ASEdrjaCUnn51tcNdmIfK9fDmr6AMFLZtunXqaVg8zmqtT7NFwrgwHutB35h8YRopaTAWNJYe8NlQrNVNxmkCPvbeM6VL8R/H/qHLWY9lzDmqR3KyPyvCO1gwG6SEp/IPvd3P+puoY4cfgCVWQuZpp5ZRauzQqeUZqXpjhhTo7CNA02OtHVf/L+NecPPZQnLoGW159s9D2JLXTtECa0pAuQ=
      file: ".pioenvs/yun/firmware.hex"
      skip_cleanup: true
      on:
        tags: true
