language: go

go:
  - 1.8.x
before_script:
  - go vet ./...
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
after_success:
- bash <(curl -s https://codecov.io/bash)