language: go

go:
  - 1.8.x
before_script:
  - go vet ./...
  - go test ./...
install:
  - go get -u github.com/mrmorphic/hwio
  - go get -u github.com/lucavallin/yfirbord-grovepi/pkg/connections
  - go get -u github.com/lucavallin/yfirbord-grovepi/pkg/io
  - go get -u github.com/lucavallin/yfirbord-grovepi/pkg/sensors
after_success:
  - codecov