language: go

go:
  - tip

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u github.com/haya14busa/goverage
  - go get -u golang.org/x/lint/golint

install:
  - dep ensure

script:
  - go vet ./...
  - golint ./...
  - go test ./...
  - goverage -v -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
