language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - dist
jobs:
  include:
  - stage: setup
    script: npm install
  - stage: lint
    script: npm run tslint
  - stage: test
    script: npm run test
  - stage: build
  - script: npm run build
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: dZ1r/52D3i7BLOqQ9EeKT7bnEWTb4QiiwAG2Keg0pqVzVpTJqi+XBy6OqqDPmrqqLOrAqZzYnXxH5bl/cd/U+pVR/bLpYXD4TUu8z1fk85QcM3oh5GhgGHZbPt+x91YHqhx2OxgyzU8LM/rSpo2dK/0FqQhbWaAwTWUburATC4HW3wpX6r9/qU4tAm3tdnsXbzCS0UoY428TLVFCM3CgDfnjNr5CCbDGa1W2hcr2TKDT1FWYSxIj4zXBWd1ClZT87bfyEvlwYpE/1n8o7Ys2oXEim0w5yfFRJvgwzXQz9vYYRZWSCC5U8poJYWmTm4vgZDwxRj9ZzmlA5EtxBWbedUay3y21GejbVmuBqo2FD/KjYxIK4lu20DOdYs10U0jJXwt5ACvW/Tm+AHC9jpV7obscSeXApiAe6hKmBwjj1cJ1ISXNeEt2H+GqlnLa35QX7/pxjwWrLU80BgstLaGty62sF2JEeqNBqMAYTOXyikN//uOSUJ0TiLK8iODbzxz6NnSoKhfBD5p5182Cxr/7V5EjdowvVna2081x06jJLIjXm1UeBbwRh4kKGMy6o4QlVbN16t3lcF0hKhWfmfYOqWKOUWZ2XglM++QiJm6F8hLbLPoFZ9oIkblO9ZrjzWSq6lW/B42OBoMMX0WdQhDxUK7/jvgRt7rjtl4qXtoL0g8=
      app: hytta-app
      skip_cleanup: true


